; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.22"

; Modules
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.1"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc3"

projects[admin_views][subdir] = "contrib"
projects[admin_views][version] = "1.1"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "2.4"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.3"

projects[chart][subdir] = "contrib"
projects[chart][version] = "1.1"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.12"

projects[date][subdir] = "contrib"
projects[date][version] = "2.6"

projects[ds][subdir] = "contrib"
projects[ds][version] = "1.8"

projects[email][subdir] = "contrib"
projects[email][version] = "1.2"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.2"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.0"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0-rc1"

projects[features_override][subdir] = "contrib"
projects[features_override][version] = "2.0-beta1"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta5"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.1"

projects[filefield_sources][subdir] = "contrib"
projects[filefield_sources][version] = "1.8"

projects[google_analytics_reports][subdir] = "contrib"
projects[google_analytics_reports][version] = "1.3"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "1.2"

projects[inline_entity_form][subdir] = "contrib"
projects[inline_entity_form][version] = "1.1"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.0"

projects[link][subdir] = "contrib"
projects[link][version] = "1.0"

projects[mediafront][subdir] = "contrib"
projects[mediafront][version] = "2.0-beta4"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.3"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "1.7"

projects[oauth][subdir] = "contrib"
projects[oauth][version] = "3.0"

projects[pasteformat][subdir] = "contrib"
projects[pasteformat][version] = "1.5"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[profiler_builder][subdir] = "contrib"
projects[profiler_builder][version] = "1.0"

projects[remote_file_source][subdir] = "contrib"
projects[remote_file_source][version] = "1.0"

projects[remote_stream_wrapper][subdir] = "contrib"
projects[remote_stream_wrapper][version] = "1.0-beta4"

projects[site_map][subdir] = "contrib"
projects[site_map][version] = "1.0"

projects[smart_trim][subdir] = "contrib"
projects[smart_trim][version] = "1.4"

projects[special_menu_items][subdir] = "contrib"
projects[special_menu_items][version] = "1.0"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[token][subdir] = "contrib"
projects[token][version] = "1.4"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"

projects[xmlsitemap][subdir] = "contrib"
projects[xmlsitemap][version] = "2.0-rc1"

; Themes
projects[adaptivetheme][version] = "2.3"

projects[cube][version] = "1.3"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[profiler][download][type] = ""
libraries[profiler][download][url] = ""
libraries[profiler][directory_name] = "profiler"
libraries[profiler][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.2/ckeditor_4.2_standard.zip "
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[FirePHPCore][download][type] = ""
libraries[FirePHPCore][download][url] = ""
libraries[FirePHPCore][directory_name] = "FirePHPCore"
libraries[FirePHPCore][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[galleria][download][type] = ""
libraries[galleria][download][url] = ""
libraries[galleria][directory_name] = "galleria"
libraries[galleria][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[getid3][download][type] = ""
libraries[getid3][download][url] = ""
libraries[getid3][directory_name] = "getid3"
libraries[getid3][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[htmlpurifier][download][type] = ""
libraries[htmlpurifier][download][url] = ""
libraries[htmlpurifier][directory_name] = "htmlpurifier"
libraries[htmlpurifier][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.easing][download][type] = ""
libraries[jquery.easing][download][url] = ""
libraries[jquery.easing][directory_name] = "jquery.easing"
libraries[jquery.easing][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.timepicker][download][type] = ""
libraries[jquery.timepicker][download][url] = ""
libraries[jquery.timepicker][directory_name] = "jquery.timepicker"
libraries[jquery.timepicker][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[json2][download][type] = ""
libraries[json2][download][url] = ""
libraries[json2][directory_name] = "json2"
libraries[json2][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jwplayer][download][type] = ""
libraries[jwplayer][download][url] = ""
libraries[jwplayer][directory_name] = "jwplayer"
libraries[jwplayer][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[mediaelement][download][type] = ""
libraries[mediaelement][download][url] = ""
libraries[mediaelement][directory_name] = "mediaelement"
libraries[mediaelement][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = ""
libraries[modernizr][download][url] = ""
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[PHPSass][download][type] = ""
libraries[PHPSass][download][url] = ""
libraries[PHPSass][directory_name] = "PHPSass"
libraries[PHPSass][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[simplehtmldom][download][type] = ""
libraries[simplehtmldom][download][url] = ""
libraries[simplehtmldom][directory_name] = "simplehtmldom"
libraries[simplehtmldom][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = ""
libraries[superfish][download][url] = ""
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[textile][download][type] = ""
libraries[textile][download][url] = ""
libraries[textile][directory_name] = "textile"
libraries[textile][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tinymce][download][type] = ""
libraries[tinymce][download][url] = ""
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[wvega-timepicker][download][type] = ""
libraries[wvega-timepicker][download][url] = ""
libraries[wvega-timepicker][directory_name] = "wvega-timepicker"
libraries[wvega-timepicker][type] = "library"

